version: 2

seeds:
  - name: dim_customers
    description: A detail of each of the company customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: loyalty_card
        tests:
          - accepted_values:
              values: ['Yes', 'No']
              config:
                severity: warn
  - name: dim_products
    description: A detail of each of the company products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null